Repository OCA/manufacture-reporting, pull requests merged in 2023-04, with the labels that each got.

#108 [14.0][UPD] switch test jobs to github actions
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: needs review, bot is merging ⏳

#101 [14.0][ADD] mrp_flattened_bom_xlsx_subcontracting_cost
  mrp_flattened_bom_xlsx_subcontracting_cost/__init__.py
  mrp_flattened_bom_xlsx_subcontracting_cost/__manifest__.py
  mrp_flattened_bom_xlsx_subcontracting_cost/models/__init__.py
  mrp_flattened_bom_xlsx_subcontracting_cost/models/mrp_bom.py
  mrp_flattened_bom_xlsx_subcontracting_cost/readme/CONTRIBUTORS.rst
  mrp_flattened_bom_xlsx_subcontracting_cost/readme/DESCRIPTION.rst
  mrp_flattened_bom_xlsx_subcontracting_cost/readme/USAGE.rst
  mrp_flattened_bom_xlsx_subcontracting_cost/report/__init__.py
  mrp_flattened_bom_xlsx_subcontracting_cost/report/flattened_bom_xlsx.py
  mrp_flattened_bom_xlsx_subcontracting_cost/static/description/icon.png
  setup/mrp_flattened_bom_xlsx_subcontracting_cost/odoo/addons/mrp_flattened_bom_xlsx_subcontracting_cost
  setup/mrp_flattened_bom_xlsx_subcontracting_cost/setup.py
Labels: approved, bot is merging ⏳

#100 [14.0][ADD] mrp_flattened_bom_xlsx_direct_labour_cost
  mrp_flattened_bom_xlsx_labour_cost/__init__.py
  mrp_flattened_bom_xlsx_labour_cost/__manifest__.py
  mrp_flattened_bom_xlsx_labour_cost/models/__init__.py
  mrp_flattened_bom_xlsx_labour_cost/models/mrp_bom.py
  mrp_flattened_bom_xlsx_labour_cost/readme/CONTRIBUTORS.rst
  mrp_flattened_bom_xlsx_labour_cost/readme/DESCRIPTION.rst
  mrp_flattened_bom_xlsx_labour_cost/readme/USAGE.rst
  mrp_flattened_bom_xlsx_labour_cost/report/__init__.py
  mrp_flattened_bom_xlsx_labour_cost/report/flattened_bom_xlsx.py
  mrp_flattened_bom_xlsx_labour_cost/static/description/icon.png
  setup/mrp_flattened_bom_xlsx_labour_cost/odoo/addons/mrp_flattened_bom_xlsx_labour_cost
  setup/mrp_flattened_bom_xlsx_labour_cost/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#105 [14.0][FIX] mrp_flattened_bom_xlsx: Create print button at installing module
  mrp_flattened_bom_xlsx/report/flattened_bom_xlsx.xml
Labels: approved, bot is merging ⏳
